In [15]:
import torch

In [16]:
def activation(x):
    """ Sigmoid activation function 
    
        Arguments
        ---------
        x: torch.Tensor
    """
    return 1/(1+torch.exp(-x))

In [19]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 5 random normal variables
features = torch.randn((1, 5))
# True weights for our data, random normal variables again
weights = torch.randn_like(features)
# and a true bias term
bias = torch.randn((1, 1))

In [20]:
#ex1
   
y = activation(torch.sum(features * weights) + bias)
print(y)


#y = activation((features * weights).sum() + bias)


tensor([[0.1595]])


In [22]:
y = activation(torch.mm(features, weights.view(5,1))+bias)
print(y)

tensor([[0.1595]])


In [23]:
### Generate some data
torch.manual_seed(7) # Set the random seed so things are predictable

# Features are 3 random normal variables
features = torch.randn((1, 3))

# Define the size of each layer in our network
n_input = features.shape[1]     # Number of input units, must match number of input features
n_hidden = 2                    # Number of hidden units 
n_output = 1                    # Number of output units

# Weights for inputs to hidden layer
W1 = torch.randn(n_input, n_hidden)
# Weights for hidden layer to output layer
W2 = torch.randn(n_hidden, n_output)

# and bias terms for hidden and output layers
B1 = torch.randn((1, n_hidden))
B2 = torch.randn((1, n_output))

In [24]:
k = activation(torch.mm(features, W1) + B1)
output = activation(torch.mm(k, W2) + B2)
print(output)

tensor([[0.3171]])


In [25]:
import numpy as np

In [26]:
a = np.random.rand(4,3)
a

array([[0.48616952, 0.17238473, 0.5909088 ],
       [0.59801144, 0.41877423, 0.20647846],
       [0.9871981 , 0.5235382 , 0.76005054],
       [0.88694809, 0.87011022, 0.43343905]])

In [27]:
b = torch.from_numpy(a)
b

tensor([[0.4862, 0.1724, 0.5909],
        [0.5980, 0.4188, 0.2065],
        [0.9872, 0.5235, 0.7601],
        [0.8869, 0.8701, 0.4334]], dtype=torch.float64)

In [28]:
b.numpy()

array([[0.48616952, 0.17238473, 0.5909088 ],
       [0.59801144, 0.41877423, 0.20647846],
       [0.9871981 , 0.5235382 , 0.76005054],
       [0.88694809, 0.87011022, 0.43343905]])

In [29]:
b.mul_(2)

tensor([[0.9723, 0.3448, 1.1818],
        [1.1960, 0.8375, 0.4130],
        [1.9744, 1.0471, 1.5201],
        [1.7739, 1.7402, 0.8669]], dtype=torch.float64)

In [30]:
a

array([[0.97233905, 0.34476945, 1.18181759],
       [1.19602288, 0.83754846, 0.41295691],
       [1.9743962 , 1.04707639, 1.52010107],
       [1.77389618, 1.74022045, 0.8668781 ]])